# Feature Encoding

Feature encoding is the process of transforming `categorical features` into `numeric features`. This is necessary because machine learning algorithms can only handle numeric features. There are many different ways to encode categorical features, and each method has its own advantages and disadvantages. In this notebook, we will explore some of the most popular methods for encoding categorical features, such as:

- Label encoding
- Ordinal encoding
- One-hot encoding
- Binary encoding

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [59]:
# data load
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## 1. **Label encoding**
This technique assigns a unique integer to each category sequentially based on alphabetical order or appearance.Mechanism: Maps N categories to integers from 0 to N-1.
Example: ["Low", "Medium", "High"]-- [0, 1, 2].
When to use: Target variables (y) only. Do not use it for input features (X) because algorithms will mistakenly assume math relationships (e.g., that "High" (2) is twice as much as "Medium" (1)).

In [60]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [61]:
# let's encode the time in labelencoder with sklearn
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
le = LabelEncoder()
df['encoded_time'] = le.fit_transform(df['time'])
df.head()

   total_bill   tip     sex smoker  day    time  size  encoded_time
0       16.99  1.01  Female     No  Sun  Dinner     2             0
1       10.34  1.66    Male     No  Sun  Dinner     3             0
2       21.01  3.50    Male     No  Sun  Dinner     3             0
3       23.68  3.31    Male     No  Sun  Dinner     2             0
4       24.59  3.61  Female     No  Sun  Dinner     4             0

In [62]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [63]:
df['encoded_time'].value_counts()

encoded_time
0    176
1     68
Name: count, dtype: int64

In [64]:
df

     total_bill   tip     sex smoker   day    time  size  encoded_time
0         16.99  1.01  Female     No   Sun  Dinner     2             0
1         10.34  1.66    Male     No   Sun  Dinner     3             0
2         21.01  3.50    Male     No   Sun  Dinner     3             0
3         23.68  3.31    Male     No   Sun  Dinner     2             0
4         24.59  3.61  Female     No   Sun  Dinner     4             0
..          ...   ...     ...    ...   ...     ...   ...           ...
239       29.03  5.92    Male     No   Sat  Dinner     3             0
240       27.18  2.00  Female    Yes   Sat  Dinner     2             0
241       22.67  2.00    Male    Yes   Sat  Dinner     2             0
242       17.82  1.75    Male     No   Sat  Dinner     2             0
243       18.78  3.00  Female     No  Thur  Dinner     2             0

[244 rows x 8 columns]

## 2. **Ordinal Encoding**   
This is a specialized version of label encoding where you manually define the integer order to preserve a known ranking or hierarchy.\
**Mechanism:** Explicitly maps categories to specific numeric scales.Example: {"Cold": 0, "Warm": 1, "Hot": 2}.\
**When to use:** Input features (X) that have a strict, inherent ranking (e.g., education level, survey responses like Likert scales, or shirt sizes).

In [65]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [66]:
# ordinal encoding the day column using specific order
oe = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']])
df['encoded_day'] = oe.fit_transform(df[['day']])
df.head(60)

,total_bill,tip,sex,smoker,day,time,size,encoded_time,encoded_day
0,16.99,1.01,Female,No,Sun,Dinner,2,0,3.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0,3.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0,3.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0,3.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0,3.0
5,25.29,4.71,Male,No,Sun,Dinner,4,0,3.0
6,8.77,2.00,Male,No,Sun,Dinner,2,0,3.0
7,26.88,3.12,Male,No,Sun,Dinner,4,0,3.0
8,15.04,1.96,Male,No,Sun,Dinner,2,0,3.0
9,14.78,3.23,Male,No,Sun,Dinner,2,0,3.0
10,10.27,1.71,Male,No,Sun,Dinner,2,0,3.0
11,35.26,5.00,Female,No,Sun,Dinner,4,0,3.0
12,15.42,1.57,Male,No,Sun,Dinner,2,0,3.0
13,18.43,3.00,Male,No,Sun,Dinner,4,0,3.0
14,14.83,3.02,Female,No,Sun,Dinner,2,0,3.0
15,21.58,3.92,Male,No,Sun,Dinner,2,0,3.0
16,10.33,1.67,Female,No,Sun,Dinner,3,0,3.0
17,16.29,3.71,Male,No,Sun,Dinner,3,0,3.0
18,16.97,3.50,Female,No,Sun,Dinner,3,0,3.0
19,20.65,3.35,Male,No,Sat,Dinner,3,0,2.0
20,17.92,4.08,Male,No,Sat,Dinner,2,0,2.0
21,20.29,2.75,Female,No,Sat,Dinner,2,0,2.0
22,15.77,2.23,Female,No,Sat,Dinner,2,0,2.0
23,39.42,7.58,Male,No,Sat,Dinner,4,0,2.0
24,19.82,3.18,Male,No,Sat,Dinner,2,0,2.0
25,17.81,2.34,Male,No,Sat,Dinner,4,0,2.0
26,13.37,2.00,Male,No,Sat,Dinner,2,0,2.0
27,12.69,2.00,Male,No,Sat,Dinner,2,0,2.0
28,21.70,4.30,Male,No,Sat,Dinner,2,0,2.0
29,19.65,3.00,Female,No,Sat,Dinner,2,0,2.0
30,9.55,1.45,Male,No,Sat,Dinner,2,0,2.0
31,18.35,2.50,Male,No,Sat,Dinner,4,0,2.0
32,15.06,3.00,Female,No,Sat,Dinner,2,0,2.0
33,20.69,2.45,Female,No,Sat,Dinner,4,0,2.0
34,17.78,3.27,Male,No,Sat,Dinner,2,0,2.0
35,24.06,3.60,Male,No,Sat,Dinner,3,0,2.0
36,16.31,2.00,Male,No,Sat,Dinner,3,0,2.0
37,16.93,3.07,Female,No,Sat,Dinner,3,0,2.0
38,18.69,2.31,Male,No,Sat,Dinner,3,0,2.0
39,31.27,5.00,Male,No,Sat,Dinner,3,0,2.0
40,16.04,2.24,Male,No,Sat,Dinner,3,0,2.0
41,17.46,2.54,Male,No,Sun,Dinner,2,0,3.0
42,13.94,3.06,Male,No,Sun,Dinner,2,0,3.0
43,9.68,1.32,Male,No,Sun,Dinner,2,0,3.0
44,30.40,5.60,Male,No,Sun,Dinner,4,0,3.0
45,18.29,3.00,Male,No,Sun,Dinner,2,0,3.0
46,22.23,5.00,Male,No,Sun,Dinner,2,0,3.0
47,32.40,6.00,Male,No,Sun,Dinner,4,0,3.0
48,28.55,2.05,Male,No,Sun,Dinner,3,0,3.0
49,18.04,3.00,Male,No,Sun,Dinner,2,0,3.0
50,12.54,2.50,Male,No,Sun,Dinner,2,0,3.0
51,10.29,2.60,Female,No,Sun,Dinner,2,0,3.0
52,34.81,5.20,Female,No,Sun,Dinner,4,0,3.0
53,9.94,1.56,Male,No,Sun,Dinner,2,0,3.0
54,25.56,4.34,Male,No,Sun,Dinner,4,0,3.0
55,19.49,3.51,Male,No,Sun,Dinner,2,0,3.0
56,38.01,3.00,Male,Yes,Sat,Dinner,4,0,2.0
57,26.41,1.50,Female,No,Sat,Dinner,2,0,2.0
58,11.24,1.76,Male,Yes,Sat,Dinner,2,0,2.0
59,48.27,6.73,Male,No,Sat,Dinner,4,0,2.0

In [67]:
df['encoded_day'].value_counts()

encoded_day
2.0    87
3.0    76
0.0    62
1.0    19
Name: count, dtype: int64

In [68]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [69]:
df['day'].value_counts().sort_index(ascending=True)

day
Thur    62
Fri     19
Sat     87
Sun     76
Name: count, dtype: int64

In [70]:
df

,total_bill,tip,sex,smoker,day,time,size,encoded_time,encoded_day
0,16.99,1.01,Female,No,Sun,Dinner,2,0,3.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0,3.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0,3.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0,3.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0,3.0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,0,2.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0,2.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0,2.0
242,17.82,1.75,Male,No,Sat,Dinner,2,0,2.0
243,18.78,3.00,Female,No,Thur,Dinner,2,0,0.0

## 3. One-Hot Encoding
This creates a new binary column (0 or 1) for every unique category in the feature.\
**Mechanism:** For N categories, it adds N columns. Only one column is active ("hot") at a time.\
**Example:** ["Red", "Blue"] becomes two columns: Is_Red [1, 0] and Is_Blue [0, 1].\
**When to use:** Nominal data (categories with no order, like countries or colors) when the total number of unique categories is low (usually <15).\
**Pitfall:** Causes the "Dummy Variable Trap" (multicollinearity) if you don't drop one column, and creates a massive, sparse matrix if used on high-cardinality data.

In [29]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [71]:
# one hot encoding on sex column
ohe = OneHotEncoder()
ohe.fit_transform(df[['sex']]).toarray()

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [72]:
# example of one hot encoding
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [41]:
titanic.isnull().sum()

survived          0
pclass            0
sex               0
age             177
sibsp             0
parch             0
fare              0
embarked          2
class             0
who               0
adult_male        0
deck            688
embark_town       2
alive             0
alone             0
embarked_C        0
embarked_Q        0
embarked_S        0
embarked_nan      0
dtype: int64

In [43]:
titanic['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [44]:
titanic.shape

(891, 19)

In [73]:
# example of one hot encoding
titanic = sns.load_dataset('titanic')
from sklearn.preprocessing import OneHotEncoder

# This works perfectly
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# onehot_encoder = OneHotEncoder(sparse_output==False) older version this use
embarked_onehot = encoder.fit_transform(titanic[['embarked']])
embarked_onehot_df = pd.DataFrame(embarked_onehot, columns=encoder.get_feature_names_out(['embarked']))
titanic = pd.concat([titanic.reset_index(drop=True), embarked_onehot_df.reset_index(drop=True)], axis=1)
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embarked_C,embarked_Q,embarked_S,embarked_nan
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.0,0.0,1.0,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.0,0.0,0.0,0.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.0,0.0,1.0,0.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0.0,0.0,1.0,0.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,0.0,1.0,0.0

In [74]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,embarked_C,embarked_Q,embarked_S,embarked_nan
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.0,0.0,1.0,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.0,0.0,0.0,0.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.0,0.0,1.0,0.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0.0,0.0,1.0,0.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0.0,0.0,1.0,0.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0.0,0.0,1.0,0.0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,0.0,0.0,1.0,0.0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1.0,0.0,0.0,0.0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.0,1.0,0.0,0.0

In [ ]:
# !pip install category_encoders

## 4. Binary Encoding
This is an advanced technique that combines the memory efficiency of hashing/integers with the distance safety of one-hot encoding.\
**Mechanism:** 
1. Converts categories to integers ([1, 2, 3]).
2. Converts those integers into binary digits ([01, 10, 11]).
3. Splits the binary digits into separate structural columns.

**Example:** A feature with 4 categories fits into just 2 columns instead of 4 one-hot columns.\
**When to use:** High-cardinality nominal features (e.g., Zip codes, IP addresses, or city names with hundreds of unique values) to save memory and prevent the curse of dimensionality.

In [75]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [76]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [77]:
from category_encoders import BinaryEncoder

binary_encoder = BinaryEncoder()
df_binary = binary_encoder.fit_transform(df['day'])

In [47]:
df_binary

     day_0  day_1  day_2
0        0      0      1
1        0      0      1
2        0      0      1
3        0      0      1
4        0      0      1
..     ...    ...    ...
239      0      1      0
240      0      1      0
241      0      1      0
242      0      1      0
243      0      1      1

[244 rows x 3 columns]

## Assignment: how many types of feature encoding are there?

## Assignment: When to use which type of feature encoding?

**pandas** provides quick, built-in functions to encode features without importing external libraries like scikit-learn. It is ideal for rapid data exploration and preprocessing.

In [55]:
# use pandas for feature encoding

df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [56]:
# use pandas get dummies
get_dummies = pd.get_dummies(df, columns=['day'])
get_dummies.head()

,total_bill,tip,sex,smoker,time,size,day_Thur,day_Fri,day_Sat,day_Sun
0,16.99,1.01,Female,No,Dinner,2,False,False,False,True
1,10.34,1.66,Male,No,Dinner,3,False,False,False,True
2,21.01,3.50,Male,No,Dinner,3,False,False,False,True
3,23.68,3.31,Male,No,Dinner,2,False,False,False,True
4,24.59,3.61,Female,No,Dinner,4,False,False,False,True

In [57]:
get_dummies

,total_bill,tip,sex,smoker,time,size,day_Thur,day_Fri,day_Sat,day_Sun
0,16.99,1.01,Female,No,Dinner,2,False,False,False,True
1,10.34,1.66,Male,No,Dinner,3,False,False,False,True
2,21.01,3.50,Male,No,Dinner,3,False,False,False,True
3,23.68,3.31,Male,No,Dinner,2,False,False,False,True
4,24.59,3.61,Female,No,Dinner,4,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Dinner,3,False,False,True,False
240,27.18,2.00,Female,Yes,Dinner,2,False,False,True,False
241,22.67,2.00,Male,Yes,Dinner,2,False,False,True,False
242,17.82,1.75,Male,No,Dinner,2,False,False,True,False
243,18.78,3.00,Female,No,Dinner,2,True,False,False,False